#spring:
#  config:
#    version: inject-test
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.2.3:23306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#common:
#  version: inject-test